---
- name: Spawn VM
  command: virt-install
    --name {{ inventory_hostname }}
    --location {{ centos_url }}
    --network bridge=br-node
    --network bridge=br-nfs
    --network bridge=br-iscsia
    --network bridge=br-iscsib
    --extra-args ip=::::{{ inventory_hostname }}:eth0:dhcp
    --extra-args ks={{ centos_vhost_ks }}
    --serial pty
    --nographics
    --extra-args console=tty0
    --extra-args console=ttyS0,115200
    --ram={{ ram }}
    --vcpus={{ cpus }}
    --disk size={{ disk_size }}
    --cpu host-passthrough
    --os-type=linux
    --os-variant=centos7.0
    --noautoconsole
    --wait -1
  ignore_errors: yes
  delegate_to: "{{ hostvars[groups['aio'][0]]['inventory_hostname'] }}"

- wait_for_connection:

- setup:
