---

- name: Copy virtual IP config file
  copy:
    src: /etc/sysconfig/network-scripts/ifcfg-eth0
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0:0
    remote_src: True

- name: Rewrite virtual IP config file
  replace:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0:0
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - regexp: eth0
      replace: eth0:0
    - regexp: "{{ ns_ip | regex_escape() }}"
      replace: "{{ dnsmasq_ip }}"
  notify: Restart networking

- name: Disable NetworkManager
  systemd:
    state: stopped
    name: NetworkManager
    enabled: no

- name: Enable Network scripts
  systemd:
    name: network
    enabled: yes
  notify: Restart networking

- name: Force networking restart before we continue
  meta: flush_handlers
