---
- name: Spawn ns
  command: virt-install
    --name {{ inventory_hostname }}
    --location {{ centos_url }}
    --network bridge=br-node
    --extra-args ip={{ ns_ip }}::{{ networks.node.gateway | ipaddr('address') }}:{{ networks.node.cidr | ipaddr('netmask') }}:{{ inventory_hostname }}:eth0:none:1500
    --network bridge=br-nfs
    --extra-args ip={{ networks.nfs.cidr | ipaddr(networks.nfs.start_index) | ipaddr('address') }}::{{ networks.nfs.gateway | default('') | ipaddr('address') | default('', True) }}:{{ networks.nfs.cidr | ipaddr('netmask') | default('') }}::eth1:none:{{ networks.nfs.mtu | default('1500') }}
    --network bridge=br-iscsia
    --extra-args ip={{ networks.iscsia.cidr | ipaddr(networks.iscsia.start_index) | ipaddr('address') }}::{{ networks.iscsia.gateway | default('') | ipaddr('address') | default('', True) }}:{{ networks.iscsia.cidr | ipaddr('netmask') }}::eth2:none:{{ networks.iscsia.mtu | default('1500') }}
    --network bridge=br-iscsib
    --extra-args ip={{ networks.iscsib.cidr | ipaddr(networks.iscsib.start_index) | ipaddr('address') }}::{{ networks.iscsib.gateway | default('') | ipaddr('address') | default('', True) }}:{{ networks.iscsib.cidr | ipaddr('netmask') }}::eth3:none:{{ networks.iscsib.mtu | default('1500') }}
    --extra-args bootdev=eth0
    --extra-args ksdevice=bootif
    --extra-args nameserver={{ hostvars[groups['aio'][0]]['ansible_dns']['nameservers'][0] }}
    --extra-args nameserver={{ hostvars[groups['aio'][0]]['ansible_dns']['nameservers'][1] }}
    --extra-args rd.neednet=1
    --extra-args ks={{ centos_vhost_ks }}
    --serial pty
    --nographics
    --extra-args console=tty0
    --extra-args console=ttyS0,115200
    --ram=2048
    --vcpus=1
    --disk size=16
    --cpu host-passthrough
    --os-type=linux
    --os-variant=centos7.0
    --noautoconsole
    --wait -1
  ignore_errors: yes
  delegate_to: "{{ hostvars[groups['aio'][0]]['inventory_hostname'] }}"
